{"tcc_new":{"parameters":[],"result":"pointer"},"tcc_set_output_type":{"parameters":["pointer","i32"],"pointers":["TCCState*"],"result":"i32"},"tcc_set_options":{"parameters":["pointer","pointer"],"pointers":["TCCState*","const char*"],"result":"void"},"tcc_add_include_path":{"parameters":["pointer","pointer"],"pointers":["TCCState*","const char*"],"result":"void"},"tcc_compile_string":{"parameters":["pointer","pointer"],"pointers":["TCCState*","const char*"],"result":"i32"},"tcc_relocate":{"parameters":["pointer","pointer"],"pointers":["TCCState*","void*"],"result":"i32"},"tcc_get_symbol":{"parameters":["pointer","pointer"],"pointers":["TCCState*","const char*"],"result":"pointer"}}

// [do not edit,<auto-generated />]
// This file has been automatically generated, please do not change unless you disable auto-generation in the Makefile  
#include <tcc.h>
#include <spin.h>

namespace spin {
namespace tcc {

void tcc_newSlow(const FunctionCallbackInfo<Value> &args) {
  Isolate *isolate = args.GetIsolate();

  void* rc = tcc_new();
  args.GetReturnValue().Set(Number::New(isolate, reinterpret_cast<uint64_t>(rc)));
}

void tcc_newFast(void* p, struct FastApiTypedArray* const p_ret) {

  void* r = tcc_new();
  ((void**)p_ret->data)[0] = r;

}

void tcc_set_output_typeSlow(const FunctionCallbackInfo<Value> &args) {
  Isolate *isolate = args.GetIsolate();

  Local<Context> context = isolate->GetCurrentContext();
  TCCState* v0 = reinterpret_cast<TCCState*>((uint64_t)args[0]->NumberValue(context).ToChecked());
  int32_t v1 = Local<Integer>::Cast(args[1])->Value();
  int32_t rc = tcc_set_output_type(v0, v1);
  args.GetReturnValue().Set(Number::New(isolate, rc));
}

int32_t tcc_set_output_typeFast(void* p, void* p0, int32_t p1) {
  TCCState* v0 = reinterpret_cast<TCCState*>(p0);
  int32_t v1 = p1;
  return tcc_set_output_type(v0, v1);
}

void tcc_set_optionsSlow(const FunctionCallbackInfo<Value> &args) {
  Isolate *isolate = args.GetIsolate();

  Local<Context> context = isolate->GetCurrentContext();
  TCCState* v0 = reinterpret_cast<TCCState*>((uint64_t)args[0]->NumberValue(context).ToChecked());
  const char* v1 = reinterpret_cast<const char*>((uint64_t)args[1]->NumberValue(context).ToChecked());
  tcc_set_options(v0, v1);
}

void tcc_set_optionsFast(void* p, void* p0, void* p1, struct FastApiTypedArray* const p_ret) {
  TCCState* v0 = reinterpret_cast<TCCState*>(p0);
  const char* v1 = reinterpret_cast<const char*>(p1);
  tcc_set_options(v0, v1);
}

void tcc_add_include_pathSlow(const FunctionCallbackInfo<Value> &args) {
  Isolate *isolate = args.GetIsolate();

  Local<Context> context = isolate->GetCurrentContext();
  TCCState* v0 = reinterpret_cast<TCCState*>((uint64_t)args[0]->NumberValue(context).ToChecked());
  const char* v1 = reinterpret_cast<const char*>((uint64_t)args[1]->NumberValue(context).ToChecked());
  tcc_add_include_path(v0, v1);
}

void tcc_add_include_pathFast(void* p, void* p0, void* p1, struct FastApiTypedArray* const p_ret) {
  TCCState* v0 = reinterpret_cast<TCCState*>(p0);
  const char* v1 = reinterpret_cast<const char*>(p1);
  tcc_add_include_path(v0, v1);
}

void tcc_compile_stringSlow(const FunctionCallbackInfo<Value> &args) {
  Isolate *isolate = args.GetIsolate();

  Local<Context> context = isolate->GetCurrentContext();
  TCCState* v0 = reinterpret_cast<TCCState*>((uint64_t)args[0]->NumberValue(context).ToChecked());
  const char* v1 = reinterpret_cast<const char*>((uint64_t)args[1]->NumberValue(context).ToChecked());
  int32_t rc = tcc_compile_string(v0, v1);
  args.GetReturnValue().Set(Number::New(isolate, rc));
}

int32_t tcc_compile_stringFast(void* p, void* p0, void* p1) {
  TCCState* v0 = reinterpret_cast<TCCState*>(p0);
  const char* v1 = reinterpret_cast<const char*>(p1);
  return tcc_compile_string(v0, v1);
}

void tcc_relocateSlow(const FunctionCallbackInfo<Value> &args) {
  Isolate *isolate = args.GetIsolate();

  Local<Context> context = isolate->GetCurrentContext();
  TCCState* v0 = reinterpret_cast<TCCState*>((uint64_t)args[0]->NumberValue(context).ToChecked());
  void* v1 = reinterpret_cast<void*>((uint64_t)args[1]->NumberValue(context).ToChecked());
  int32_t rc = tcc_relocate(v0, v1);
  args.GetReturnValue().Set(Number::New(isolate, rc));
}

int32_t tcc_relocateFast(void* p, void* p0, void* p1) {
  TCCState* v0 = reinterpret_cast<TCCState*>(p0);
  void* v1 = reinterpret_cast<void*>(p1);
  return tcc_relocate(v0, v1);
}

void tcc_get_symbolSlow(const FunctionCallbackInfo<Value> &args) {
  Isolate *isolate = args.GetIsolate();

  Local<Context> context = isolate->GetCurrentContext();
  TCCState* v0 = reinterpret_cast<TCCState*>((uint64_t)args[0]->NumberValue(context).ToChecked());
  const char* v1 = reinterpret_cast<const char*>((uint64_t)args[1]->NumberValue(context).ToChecked());
  void* rc = tcc_get_symbol(v0, v1);
  args.GetReturnValue().Set(Number::New(isolate, reinterpret_cast<uint64_t>(rc)));
}

void tcc_get_symbolFast(void* p, void* p0, void* p1, struct FastApiTypedArray* const p_ret) {
  TCCState* v0 = reinterpret_cast<TCCState*>(p0);
  const char* v1 = reinterpret_cast<const char*>(p1);
  void* r = tcc_get_symbol(v0, v1);
  ((void**)p_ret->data)[0] = r;

}

void Init(Isolate* isolate, Local<ObjectTemplate> target) {
  Local<ObjectTemplate> module = ObjectTemplate::New(isolate);

  v8::CTypeInfo* cargstcc_new = (v8::CTypeInfo*)calloc(1, sizeof(v8::CTypeInfo));
  cargstcc_new[0] = v8::CTypeInfo(v8::CTypeInfo::Type::kV8Value);

  v8::CTypeInfo* rctcc_new = new v8::CTypeInfo(v8::CTypeInfo::Type::kUint64);
  v8::CFunctionInfo* infotcc_new = new v8::CFunctionInfo(*rctcc_new, 1, cargstcc_new);
  v8::CFunction* pFtcc_new = new v8::CFunction((const void*)&tcc_newFast, infotcc_new);
  SET_FAST_METHOD(isolate, module, "tcc_new", pFtcc_new, tcc_newSlow);

  v8::CTypeInfo* cargstcc_set_output_type = (v8::CTypeInfo*)calloc(3, sizeof(v8::CTypeInfo));
  cargstcc_set_output_type[0] = v8::CTypeInfo(v8::CTypeInfo::Type::kV8Value);
  cargstcc_set_output_type[1] = v8::CTypeInfo(v8::CTypeInfo::Type::kUint64);
  cargstcc_set_output_type[2] = v8::CTypeInfo(v8::CTypeInfo::Type::kInt32);
  v8::CTypeInfo* rctcc_set_output_type = new v8::CTypeInfo(v8::CTypeInfo::Type::kInt32);
  v8::CFunctionInfo* infotcc_set_output_type = new v8::CFunctionInfo(*rctcc_set_output_type, 3, cargstcc_set_output_type);
  v8::CFunction* pFtcc_set_output_type = new v8::CFunction((const void*)&tcc_set_output_typeFast, infotcc_set_output_type);
  SET_FAST_METHOD(isolate, module, "tcc_set_output_type", pFtcc_set_output_type, tcc_set_output_typeSlow);

  v8::CTypeInfo* cargstcc_set_options = (v8::CTypeInfo*)calloc(3, sizeof(v8::CTypeInfo));
  cargstcc_set_options[0] = v8::CTypeInfo(v8::CTypeInfo::Type::kV8Value);
  cargstcc_set_options[1] = v8::CTypeInfo(v8::CTypeInfo::Type::kUint64);
  cargstcc_set_options[2] = v8::CTypeInfo(v8::CTypeInfo::Type::kUint64);
  v8::CTypeInfo* rctcc_set_options = new v8::CTypeInfo(v8::CTypeInfo::Type::kVoid);
  v8::CFunctionInfo* infotcc_set_options = new v8::CFunctionInfo(*rctcc_set_options, 3, cargstcc_set_options);
  v8::CFunction* pFtcc_set_options = new v8::CFunction((const void*)&tcc_set_optionsFast, infotcc_set_options);
  SET_FAST_METHOD(isolate, module, "tcc_set_options", pFtcc_set_options, tcc_set_optionsSlow);

  v8::CTypeInfo* cargstcc_add_include_path = (v8::CTypeInfo*)calloc(3, sizeof(v8::CTypeInfo));
  cargstcc_add_include_path[0] = v8::CTypeInfo(v8::CTypeInfo::Type::kV8Value);
  cargstcc_add_include_path[1] = v8::CTypeInfo(v8::CTypeInfo::Type::kUint64);
  cargstcc_add_include_path[2] = v8::CTypeInfo(v8::CTypeInfo::Type::kUint64);
  v8::CTypeInfo* rctcc_add_include_path = new v8::CTypeInfo(v8::CTypeInfo::Type::kVoid);
  v8::CFunctionInfo* infotcc_add_include_path = new v8::CFunctionInfo(*rctcc_add_include_path, 3, cargstcc_add_include_path);
  v8::CFunction* pFtcc_add_include_path = new v8::CFunction((const void*)&tcc_add_include_pathFast, infotcc_add_include_path);
  SET_FAST_METHOD(isolate, module, "tcc_add_include_path", pFtcc_add_include_path, tcc_add_include_pathSlow);

  v8::CTypeInfo* cargstcc_compile_string = (v8::CTypeInfo*)calloc(3, sizeof(v8::CTypeInfo));
  cargstcc_compile_string[0] = v8::CTypeInfo(v8::CTypeInfo::Type::kV8Value);
  cargstcc_compile_string[1] = v8::CTypeInfo(v8::CTypeInfo::Type::kUint64);
  cargstcc_compile_string[2] = v8::CTypeInfo(v8::CTypeInfo::Type::kUint64);
  v8::CTypeInfo* rctcc_compile_string = new v8::CTypeInfo(v8::CTypeInfo::Type::kInt32);
  v8::CFunctionInfo* infotcc_compile_string = new v8::CFunctionInfo(*rctcc_compile_string, 3, cargstcc_compile_string);
  v8::CFunction* pFtcc_compile_string = new v8::CFunction((const void*)&tcc_compile_stringFast, infotcc_compile_string);
  SET_FAST_METHOD(isolate, module, "tcc_compile_string", pFtcc_compile_string, tcc_compile_stringSlow);

  v8::CTypeInfo* cargstcc_relocate = (v8::CTypeInfo*)calloc(3, sizeof(v8::CTypeInfo));
  cargstcc_relocate[0] = v8::CTypeInfo(v8::CTypeInfo::Type::kV8Value);
  cargstcc_relocate[1] = v8::CTypeInfo(v8::CTypeInfo::Type::kUint64);
  cargstcc_relocate[2] = v8::CTypeInfo(v8::CTypeInfo::Type::kUint64);
  v8::CTypeInfo* rctcc_relocate = new v8::CTypeInfo(v8::CTypeInfo::Type::kInt32);
  v8::CFunctionInfo* infotcc_relocate = new v8::CFunctionInfo(*rctcc_relocate, 3, cargstcc_relocate);
  v8::CFunction* pFtcc_relocate = new v8::CFunction((const void*)&tcc_relocateFast, infotcc_relocate);
  SET_FAST_METHOD(isolate, module, "tcc_relocate", pFtcc_relocate, tcc_relocateSlow);

  v8::CTypeInfo* cargstcc_get_symbol = (v8::CTypeInfo*)calloc(3, sizeof(v8::CTypeInfo));
  cargstcc_get_symbol[0] = v8::CTypeInfo(v8::CTypeInfo::Type::kV8Value);
  cargstcc_get_symbol[1] = v8::CTypeInfo(v8::CTypeInfo::Type::kUint64);
  cargstcc_get_symbol[2] = v8::CTypeInfo(v8::CTypeInfo::Type::kUint64);
  v8::CTypeInfo* rctcc_get_symbol = new v8::CTypeInfo(v8::CTypeInfo::Type::kUint64);
  v8::CFunctionInfo* infotcc_get_symbol = new v8::CFunctionInfo(*rctcc_get_symbol, 3, cargstcc_get_symbol);
  v8::CFunction* pFtcc_get_symbol = new v8::CFunction((const void*)&tcc_get_symbolFast, infotcc_get_symbol);
  SET_FAST_METHOD(isolate, module, "tcc_get_symbol", pFtcc_get_symbol, tcc_get_symbolSlow);
  SET_MODULE(isolate, target, "tcc", module);
}
} // namespace tcc
} // namespace spin

extern "C" {
  void* _register_tcc() {
    return (void*)spin::tcc::Init;
  }
}
